version: 2.1

jobs:
  test_job:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: echo "It's-a me, the pizza ghost"

workflows:
  testing:
    jobs:
      - test_job
